trigger:
  branches:
    include:
      - main

pool:
  name: 'mycomputeragent'

steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud Service'
      organization: '21022609-gang'
      scannerMode: 'MSBuild'
      ProjectKey: '21022609-Gang_FYP_Project'
      ProjectName: 'FYP_Project'

  - script: echo testing
    displayName: Test

  - script: |
      echo this is the hostname:
      echo -----------------------
      echo $HOSTNAME
    displayName: Test Script 2

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '/**/obj/*.csproj'
      arguments: '--collect "Code Coverage"'

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
    
  - task: WhiteSource@21
    inputs:
      cwd: '$(System.DefaultWorkingDirectory)'
