trigger:
  branches:
    include:
      - main

schedules:
- cron: "0 19 * * *"
  displayName: Daily build
  branches:
    include:
      - main

pool:
  name: 'mycomputeragent'

steps:

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud Service'
      organization: '21022609-gang'
      scannerMode: 'MSBuild'
      ProjectKey: '21022609-Gang_FYP_Project'
      ProjectName: 'FYP_Project'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '/workspaces/FYP_Project/OurWebAppTest/*.csproj'
      feedsToUse: 'select'
      vstsFeed: 'e532e879-2c5f-49fa-8d91-4c53aac3a2ec'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '/workspaces/FYP_Project/OurWebAppTest/*.csproj'

  - script: echo testing
    displayName: Test

  - script: |
      echo this is the hostname:
      echo ------------------------
      echo $HOSTNAME
    displayName: Test Script 2

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '/workspaces/FYP_Project/OurWebAppTest/*.csproj'
      arguments: '--collect "Code Coverage"'

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
    
  - task: WhiteSource@21
    inputs:
      cwd: '$(System.DefaultWorkingDirectory)'
          
  - task: Docker@2
  - script: |
      docker build -t $DOCKERHUB_USERNAME/clockbox:latest .
      docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
      docker push $DOCKERHUB_USERNAME/clockbox:latest
