trigger:
  branches:
    include:
      - main

pool:
  name: 'mycomputeragent'

steps:
  - script: echo testing
    displayName: Test

  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'SonarQubeConnect'
      scannerMode: 'MSBuild'
      projectKey: 'SOI-2023-2310-0043-Team1_FYP_Project.git_AYhZrWKJnox9yhVTP-5B'
      projectName: 'FYP_Project'

  - script: |
      echo this is the hostname:
      echo -----------------------
      echo $HOSTNAME
    displayName: Test Script 2

  - task: WhiteSource@21
    inputs:
      cwd: '$(System.DefaultWorkingDirectory)'

  - task: SonarQubeAnalyze@5

  - task: SonarQubePublish@5
    inputs:
      pollingTimeoutSec: '300'