trigger:
  branches:
    include:
      - main

schedules:
- cron: "0 19 * * *"
  displayName: Daily build
  branches:
    include:
      - main

pool:
  name: 'mycomputeragent'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '/workspaces/FYP_Project/OurWebAppTest/*.csproj'
      feedsToUse: 'select'
      vstsFeed: 'e532e879-2c5f-49fa-8d91-4c53aac3a2ec'

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud Service'
      organization: '21022609-gang'
      scannerMode: 'MSBuild'
      ProjectKey: '21022609-Gang_FYP_Project'
      ProjectName: 'FYP_Project'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '/workspaces/FYP_Project/OurWebAppTest/*.csproj'

  - script: echo testing
    displayName: Test

  - script: |
      echo this is the hostname:
      echo ------------------------
      echo $HOSTNAME
    displayName: Test Script 2

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '/workspaces/FYP_Project/OurWebAppTest/*.csproj'
      arguments: '--collect "Code Coverage"'

  - task: SonarCloudAnalyze@1

  - task: WhiteSource@21
    inputs:
      cwd: '$(System.DefaultWorkingDirectory)'

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
    
  - task: Docker@2
    displayName : Login to Docker Hub
    inputs:
        command: login
        containerRegistry: Docker_Hub #fypproject #dockerRegistryServiceConnection1 #

  - task: DockerInstaller@0
    displayName: Docker Installer
    inputs:
        dockerVersion: 17.09.0-ce
        releaseType: stable

  - task: Docker@2
    displayName: Build and Push
    inputs:
        command: buildAndPush
        repository:   denisepzq/newimage # username/contosoRepository for DockerHub
        Dockerfile: /workspaces/FYP_Project/.devcontainer/Dockerfile #hello