trigger:
  branches:
    include:
      - main

pool:
  name: 'mycomputeragent'

steps:
  - script: echo testing
    displayName: Test

  - script: |
      echo this is the hostname:
      echo -----------------------
      echo $HOSTNAME
    displayName: Test Script 2

  - task: WhiteSource@21
    inputs:
      cwd: '$(System.DefaultWorkingDirectory)'

  - task: UseDotNet@2
    inputs:
     packageType: 'sdk'
     version: '6.x'
     includePreviewVersions: true
 
  - task: NuGetToolInstaller@1
    inputs:
     versionSpec: '5.9.0'
     checkLatest: true
 
  - task: DotNetCoreCLI@2
    inputs:
     command: 'restore'
     projects: '**/*.sln'
     feedsToUse: 'select'

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud Service'
      organization: '21022609-gang'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: '21022609-Gang_FYP_Project'
      cliProjectName: 'FYP_Project'
      cliSources: '.'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '/workspaces/FYP_Project/OurWebApp/PrototypeWebapp.cs'
      arguments: '/nr:false'

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'


