trigger:
  branches:
    include:
      - main

pool:
  name: 'mycomputeragent'

steps:
  - script: echo testing
    displayName: Test

  - script: |
      # Download and install OpenCover
      mkdir -p '$(Agent.ToolsDirectory)/OpenCover'
      Invoke-WebRequest -Uri 'https://github.com/OpenCover/opencover/releases/download/4.7.1221/opencover.4.7.1221.msi' -OutFile '$(Agent.ToolsDirectory)/OpenCover/OpenCover.exe'
      OpenCover.Console.exe -target:"path/to/your/test/executable" -output:"$(Build.ArtifactStagingDirectory)/OpenCoverResults.xml"
    displayName: Install OpenCover

  - task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'OpenCover'
    summaryFileLocation: '$(Build.ArtifactStagingDirectory)/OpenCoverResults.xml'
    reportDirectory: '$(Build.ArtifactStagingDirectory)'

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud Service'
      organization: '21022609-gang'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: '21022609-Gang_FYP_Project'
      cliProjectName: 'FYP_Project'
      extraProperties: |
      sonar.cs.opencover.reportsPaths=$(Build.ArtifactStagingDirectory)/OpenCoverResults.xml

  - script: |
      echo this is the hostname:
      echo -----------------------
      echo $HOSTNAME
    displayName: Test Script 2

  - task: WhiteSource@21
    inputs:
      cwd: '$(System.DefaultWorkingDirectory)'

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
    
