trigger:
- main

pool:
  name: 'mycomputeragent'

steps:
- script: echo testing
  displayName: 'Test'

- script: 
    echo this is the hostname
    echo ---------------------
    echo $HOSTNAME
  displayName: 'Test Script 2'