trigger:
  branches:
    include:
      - main

pool:
  name: 'mycomputeragent'

steps:
  - script: echo testing
    displayName: Test

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud Service'
      organization: '21022609-gang'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: '21022609-Gang_FYP_Project'
      cliProjectName: 'FYP_Project'

  - script: |
      echo this is the hostname:
      echo -----------------------
      echo $HOSTNAME
    displayName: Test Script 2

  - task: WhiteSource@21
    inputs:
      cwd: '$(System.DefaultWorkingDirectory)'

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'

  - script: dotnet tool install --global coverlet.console
    displayName: Install Coverlet

  - script: dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings
    displayName: Run Tests with Coverage

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*.cobertura.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/codecoverage'
