trigger:
  branches:
    include:
      - main

pool:
  name: 'mycomputeragent'

steps:
  - script: echo testing
    displayName: Test

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud Service'
      organization: '21022609-gang'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: '21022609-Gang_FYP_Project'
      cliProjectName: 'FYP_Project'

  - script: |
      echo this is the hostname:
      echo -----------------------
      echo $HOSTNAME
    displayName: Test Script 2

  - task: WhiteSource@21
    inputs:
      cwd: '$(System.DefaultWorkingDirectory)'

  - task: SonarCloudAnalyze@1

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '/workspaces/FYP_Project/OurWebApp/Tests'
      arguments: '--configuration $(BuildConfiguration) --collect "Code Coverage"'

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'


